//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autotransportes_ABC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudes
    {
        public int id_solicitud { get; set; }
        public int lote { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
